--DDL - Data Definition Language

--CRIAR UM BANCO
CREATE DATABASE Exercicio_1_2;

--USAR O BANCO CRIADO
USE Exercicio_1_2;

--CRIAR TABELAS
CREATE TABLE Cliente
(
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
	CPF VARCHAR(14) NOT NULL UNIQUE,
)

CREATE TABLE Empresa
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
)

CREATE TABLE Modelo
(
	IdModelo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
)

CREATE TABLE Marca
(
	IdMarca INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
)

CREATE TABLE Veiculo
(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa) NOT NULL,
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo) NOT NULL,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca) NOT NULL,
	Placa VARCHAR(20) NOT NULL UNIQUE
)

CREATE TABLE Aluguel
(
	IdAluguel INT PRIMARY KEY IDENTITY,
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo) NOT NULL,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente) NOT NULL,
	Protocolo VARCHAR(30) NOT NULL UNIQUE,
	DataInicio VARCHAR(30) NOT NULL UNIQUE,
	DataFinal VARCHAR(30) NOT NULL UNIQUE
)

SELECT * FROM Cliente
SELECT * FROM Aluguel
SELECT * FROM Empresa
SELECT * FROM Veiculo
SELECT * FROM Modelo
SELECT * FROM Marca