--DDL - Data Definition Language

--CRIAR UM BANCO
CREATE DATABASE Exercicio_1_4;

--USAR O BANCO CRIADO
USE Exercicio_1_4;

--CRIAR TABELAS
CREATE TABLE Artista
(
	IdArtista INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
)

CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
	Email VARCHAR(20) NOT NULL,
	Senha VARCHAR(20) NOT NULL,
	Permissao VARCHAR(20) NOT NULL
)

CREATE TABLE Estilos
(
	IdEstilos INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
)


CREATE TABLE Album
(
	IdAlbum INT PRIMARY KEY IDENTITY,
	IdArtista INT FOREIGN KEY REFERENCES Artista(IdArtista) NOT NULL,
	Titulo VARCHAR(20) NOT NULL,
	DataLancamento VARCHAR(20) NOT NULL,
	Localizacao VARCHAR(20) NOT NULL,
	QtdMinutos VARCHAR(20) NOT NULL,
	Ativos VARCHAR(20) NOT NULL,
)

CREATE TABLE AlbunsEstilos
(
	IdAlbum INT FOREIGN KEY REFERENCES Album(IdAlbum) NOT NULL,
	IdEstilos INT FOREIGN KEY REFERENCES Estilos(IdEstilos) NOT NULL,
)


SELECT * FROM Artista
SELECT * FROM Usuario
SELECT * FROM Estilos
SELECT * FROM Album
SELECT * FROM AlbunsEstilos